### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by Leslie-C** [Apb58/motif-mark#13]
```
(python35) [02:18:09:motif-mark] $ ./Motif_Marker.py -f test/fasta_t1.fa -m test/motifs.txt 
Traceback (most recent call last):
  File "./Motif_Marker.py", line 256, in <module>
    results = Motif_search(fasta_sequence(to_process), args.w, Motifs)
  File "./Motif_Marker.py", line 116, in Motif_search
    w_seq = window_trim(fasta, window)
  File "./Motif_Marker.py", line 93, in window_trim
    exon_bounds = fasta.exon_bounds()
  File "./Motif_Marker.py", line 50, in exon_bounds
    exon_st = self.seq.find(re.search('[ATCG]+',self.seq)[0])
TypeError: '_sre.SRE_Match' object is not subscriptable
```

**Comment by Leslie-C** [comment]
Not compatible with python3.5

**Comment by Apb58** [comment]
Updated -- see version Motif_Marker_3.4.py -- this should run with 3.4/3.5 (an issue with re being unable to use indexing in earlier versions; fixed here using '.group()')
